import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#d2d0cf",
        "on-secondary": "#525151",
        "outline-variant": "#484848",
        "surface-container-lowest": "#000000",
        "secondary-dim": "#d6d4d3",
        "on-background": "#ffffff",
        "tertiary-dim": "#e22800",
        "surface": "#0e0e0e",
        "primary-fixed-dim": "#efc900",
        "error-container": "#b92902",
        "background": "#0e0e0e",
        "on-primary-fixed-variant": "#665500",
        "outline": "#757575",
        "on-tertiary": "#460600",
        "on-error": "#450900",
        "tertiary-container": "#fe2e00",
        "inverse-surface": "#f9f9f9",
        "surface-container-highest": "#262626",
        "surface-container-high": "#1f1f1f",
        "on-tertiary-fixed": "#370400",
        "surface-tint": "#ffe792",
        "secondary": "#e4e2e1",
        "on-secondary-fixed-variant": "#5c5b5b",
        "primary-dim": "#efc900",
        "on-primary-fixed": "#453900",
        "on-tertiary-fixed-variant": "#751000",
        "surface-variant": "#262626",
        "surface-bright": "#2c2c2c",
        "surface-container": "#191919",
        "surface-dim": "#0e0e0e",
        "surface-container-low": "#131313",
        "on-primary": "#655400",
        "inverse-on-surface": "#555555",
        "on-primary-container": "#5b4b00",
        "tertiary": "#ff7256",
        "secondary-fixed-dim": "#d6d4d3",
        "secondary-container": "#474746",
        "on-tertiary-container": "#000000",
        "on-surface": "#ffffff",
        "error": "#ff7351",
        "on-secondary-fixed": "#3f3f3f",
        "primary": "#ffe792",
        "on-error-container": "#ffd2c8",
        "primary-fixed": "#ffd709",
        "on-surface-variant": "#ababab",
        "primary-container": "#ffd709",
        "tertiary-fixed": "#ff937d",
        "secondary-fixed": "#e4e2e1",
        "error-dim": "#d53d18",
        "tertiary-fixed-dim": "#ff7c62",
        "inverse-primary": "#705e00",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      animation: {
        marquee: "marquee 20s linear infinite",
      },
    },
  },
  plugins: [],
};

export default config;
